// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nsia.Data;

#nullable disable

namespace nsia.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260514024643_NewQuestionBank")]
    partial class NewQuestionBank
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("nsia.Models.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("nsia.Models.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AccessForUnderserved")
                        .HasColumnType("longtext");

                    b.Property<string>("AccessibilityForDisadvantaged")
                        .HasColumnType("longtext");

                    b.Property<string>("ActivePartnerships")
                        .HasColumnType("longtext");

                    b.Property<string>("AdditionalInformation")
                        .HasColumnType("text");

                    b.Property<bool>("AgreesToPrivacyPolicy")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AgreesToTermsOfService")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ApplicationStep")
                        .HasColumnType("int");

                    b.Property<string>("AverageCAC")
                        .HasColumnType("longtext");

                    b.Property<string>("BeneficiaryInvolvement")
                        .HasColumnType("longtext");

                    b.Property<string>("BiggestRisks")
                        .HasColumnType("longtext");

                    b.Property<string>("BusinessLga")
                        .HasColumnType("longtext");

                    b.Property<string>("BusinessReplicability")
                        .HasColumnType("longtext");

                    b.Property<string>("BusinessSector")
                        .HasColumnType("longtext");

                    b.Property<string>("BusinessState")
                        .HasColumnType("longtext");

                    b.Property<string>("ClimateChangeApproach")
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyHqAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyName")
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyRegistrationNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyStructure")
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyValuation")
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyWebsite")
                        .HasColumnType("longtext");

                    b.Property<string>("CoreBusinessModel")
                        .HasColumnType("longtext");

                    b.Property<string>("CountryOfOrigin")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CrossIndustryApplication")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerGrowthRate")
                        .HasColumnType("longtext");

                    b.Property<string>("DataProtection")
                        .HasColumnType("longtext");

                    b.Property<string>("DemandEvidence")
                        .HasColumnType("longtext");

                    b.Property<string>("DigitalAccessibility")
                        .HasColumnType("longtext");

                    b.Property<string>("DiversityInclusion")
                        .HasColumnType("longtext");

                    b.Property<string>("DocumentDetails")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EmailVerificationOtp")
                        .HasColumnType("longtext");

                    b.Property<string>("EnergyWasteReduction")
                        .HasColumnType("longtext");

                    b.Property<string>("EquitableOpportunities")
                        .HasColumnType("longtext");

                    b.Property<string>("EthicalOperations")
                        .HasColumnType("longtext");

                    b.Property<string>("ExistingUsers")
                        .HasColumnType("longtext");

                    b.Property<string>("ExternalFunding")
                        .HasColumnType("longtext");

                    b.Property<string>("FounderIndustryExperience")
                        .HasColumnType("longtext");

                    b.Property<string>("FoundingTeamType")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("GenderGapApproach")
                        .HasColumnType("longtext");

                    b.Property<string>("GeographicScalability")
                        .HasColumnType("longtext");

                    b.Property<string>("GeographicScope")
                        .HasColumnType("longtext");

                    b.Property<string>("GrossMargins")
                        .HasColumnType("longtext");

                    b.Property<string>("GrowthStage")
                        .HasColumnType("longtext");

                    b.Property<string>("HasForeignAffiliates")
                        .HasColumnType("longtext");

                    b.Property<string>("HasStartedGeneratingSales")
                        .HasColumnType("longtext");

                    b.Property<string>("ImpactDataSharing")
                        .HasColumnType("longtext");

                    b.Property<string>("IpOwnership")
                        .HasColumnType("longtext");

                    b.Property<string>("IsCurrentlyFundraising")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IsNigerianEntityPrimary")
                        .HasColumnType("longtext");

                    b.Property<string>("IsRegisteredInNigeria")
                        .HasColumnType("longtext");

                    b.Property<string>("JobsCreated")
                        .HasColumnType("longtext");

                    b.Property<string>("KeyFeatures")
                        .HasColumnType("longtext");

                    b.Property<string>("KeyMilestones")
                        .HasColumnType("longtext");

                    b.Property<string>("LongTermGrowthStrategy")
                        .HasColumnType("longtext");

                    b.Property<string>("MainCompetitors")
                        .HasColumnType("longtext");

                    b.Property<string>("ManagementTeamExperience")
                        .HasColumnType("longtext");

                    b.Property<string>("MarketPenetrationStrategy")
                        .HasColumnType("longtext");

                    b.Property<string>("NewCustomersSixMonths")
                        .HasColumnType("longtext");

                    b.Property<string>("NinEncrypted")
                        .HasColumnType("longtext");

                    b.Property<string>("NumberOfFounders")
                        .HasColumnType("longtext");

                    b.Property<string>("OperatingRunway")
                        .HasColumnType("longtext");

                    b.Property<string>("OtherCompetitions")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("OtpExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ParentOrganizationName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("PopulationImpacted")
                        .HasColumnType("longtext");

                    b.Property<string>("PricingStrategy")
                        .HasColumnType("longtext");

                    b.Property<string>("PrimaryCompetitiveAdvantage")
                        .HasColumnType("longtext");

                    b.Property<string>("ProjectedRevenue")
                        .HasColumnType("longtext");

                    b.Property<string>("ProprietaryFunding")
                        .HasColumnType("longtext");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RegulatoryApproach")
                        .HasColumnType("longtext");

                    b.Property<string>("RegulatoryCompliance")
                        .HasColumnType("longtext");

                    b.Property<string>("RelationshipToBusiness")
                        .HasColumnType("longtext");

                    b.Property<string>("RepeatCustomerRevenue")
                        .HasColumnType("longtext");

                    b.Property<string>("ResourceOptimization")
                        .HasColumnType("longtext");

                    b.Property<string>("RevenueStreams")
                        .HasColumnType("longtext");

                    b.Property<string>("ScalingWithSustainability")
                        .HasColumnType("longtext");

                    b.Property<string>("SdgAlignment")
                        .HasColumnType("longtext");

                    b.Property<string>("SocialGoodContribution")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SupplyChainReliability")
                        .HasColumnType("longtext");

                    b.Property<string>("SustainabilityIntegration")
                        .HasColumnType("longtext");

                    b.Property<string>("SustainabilityTechnology")
                        .HasColumnType("longtext");

                    b.Property<string>("SystemicInequalityApproach")
                        .HasColumnType("longtext");

                    b.Property<string>("TaxCompliance")
                        .HasColumnType("longtext");

                    b.Property<string>("TotalFullTimeEmployees")
                        .HasColumnType("longtext");

                    b.Property<string>("TotalUsersReached")
                        .HasColumnType("longtext");

                    b.Property<string>("TypesOfFunding")
                        .HasColumnType("longtext");

                    b.Property<string>("UnderservedMarketPercentage")
                        .HasColumnType("longtext");

                    b.Property<string>("UniqueSellingPoint")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("YearOfFirstSale")
                        .HasColumnType("longtext");

                    b.Property<string>("YearlyProfit")
                        .HasColumnType("longtext");

                    b.Property<string>("YearlySalesRevenue")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationStep")
                        .HasDatabaseName("IX_Applications_ApplicationStep");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Applications_CreatedAt");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Applications_Email");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Applications_ReferenceNumber");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Applications_Status");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("nsia.Models.ApplicationDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StoredFilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("ApplicationDocuments");
                });

            modelBuilder.Entity("nsia.Models.Founder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("char(36)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Nationality")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("IX_Founders_ApplicationId");

                    b.HasIndex("ApplicationId", "DisplayOrder")
                        .HasDatabaseName("IX_Founders_ApplicationId_DisplayOrder");

                    b.ToTable("Founders");
                });

            modelBuilder.Entity("nsia.Models.Application", b =>
                {
                    b.OwnsOne("nsia.Models.SocialMedia", "SocialMedia", b1 =>
                        {
                            b1.Property<Guid>("ApplicationId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Facebook")
                                .HasColumnType("varchar(200)")
                                .HasColumnName("SocialMedia_Facebook");

                            b1.Property<string>("Instagram")
                                .HasColumnType("varchar(100)")
                                .HasColumnName("SocialMedia_Instagram");

                            b1.Property<string>("LinkedIn")
                                .HasColumnType("varchar(200)")
                                .HasColumnName("SocialMedia_LinkedIn");

                            b1.Property<string>("Twitter")
                                .HasColumnType("varchar(100)")
                                .HasColumnName("SocialMedia_Twitter");

                            b1.HasKey("ApplicationId");

                            b1.ToTable("Applications");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");
                        });

                    b.Navigation("SocialMedia");
                });

            modelBuilder.Entity("nsia.Models.ApplicationDocument", b =>
                {
                    b.HasOne("nsia.Models.Application", "Application")
                        .WithMany("Documents")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("nsia.Models.Founder", b =>
                {
                    b.HasOne("nsia.Models.Application", "Application")
                        .WithMany("Founders")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("nsia.Models.Application", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Founders");
                });
#pragma warning restore 612, 618
        }
    }
}
