// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nsia.Data;

#nullable disable

namespace nsia.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260425203345_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("nsia.Models.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AccessForUnderservedGroups")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("ActivePartnerships")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("AdditionalInformation")
                        .HasMaxLength(3000)
                        .HasColumnType("text");

                    b.Property<bool>("AgreesToCompetitionSubmissionAgreement")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AgreesToNsiaPrivacyPolicy")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("AlignsWithUnSdgs")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ApplicationStep")
                        .HasColumnType("int");

                    b.Property<string>("AverageCustomerAcquisitionCost")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("BeneficiaryInvolvementLevel")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("BiggestRisks")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BusinessAddress")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("BusinessModel")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CacRegistrationNumber")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("CompanyDescription")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CompanyUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("CompanyValuation")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CrisisPerformance")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CrossIndustryApplicability")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CustomerGrowthRatePastYear")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CustomersAcquiredPastSixMonths")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DataProtectionApproach")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DemandEvidence")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DocumentDetails")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("EmailVerificationOtp")
                        .HasColumnType("longtext");

                    b.Property<string>("EnvironmentalHarmReduction")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("EstimatedMarketShare")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("EthicalPracticesApproach")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("FeedbackUpdateFrequency")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ForeignAffiliateDetails")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FundingTypes")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("GenderGapApproach")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("GeographicScalability")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GoToMarketStrategy")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("GrossMargins")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("GrowthStage")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("HasForeignAffiliates")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("HasStartedGeneratingRevenue")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ImpactDataAndStatistics")
                        .HasColumnType("text");

                    b.Property<string>("ImpactDataSharingLevel")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ImpactDurability")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("ImpactMeasurementMethod")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("IpOwnership")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool?>("IsCurrentlyFundraising")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsLegallyRegisteredInNigeria")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsNigerianEntityOperational")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JobsCreated")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("KeyFeatures")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LocalContextTailoring")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LongTermGrowthPlan")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LongTermVision")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MainCompetitors")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MeasurableCommunityDifferences")
                        .HasColumnType("text");

                    b.Property<string>("Milestones")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ModelReplicability")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MvpLink")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("NumberOfFounders")
                        .HasColumnType("int");

                    b.Property<string>("OperatingRunway")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("OtpExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PeopleImpacted")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PolicyAdvocacy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PricingStrategy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PrimaryCompetitiveEdge")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("text");

                    b.Property<string>("ProjectedRevenueNextYear")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("ReducesEnvironmentalHarm")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RegulatoryCompliance")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RepeatCustomerRevenuePercentage")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ResourceOptimisation")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RevenueStreams")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SdgsAddressed")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Sector")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SocialOutcomeTracking")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SuccessMetrics")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SupplyChainReliability")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SystemicInequalityReduction")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TeamComposition")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TopImpactExamplesDetails")
                        .HasColumnType("text");

                    b.Property<int?>("TotalEmployees")
                        .HasColumnType("int");

                    b.Property<string>("TrustBuildingApproach")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("UnderservedMarketPercentage")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UniqueSellingPoint")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserCountRange")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("UserSelfRelianceLevel")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("YearOfIncorporation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationStep")
                        .HasDatabaseName("IX_Applications_ApplicationStep");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Applications_CreatedAt");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Applications_Email");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Applications_ReferenceNumber");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Applications_Status");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("nsia.Models.ApplicationDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StoredFilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("ApplicationDocuments");
                });

            modelBuilder.Entity("nsia.Models.Founder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("char(36)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("IX_Founders_ApplicationId");

                    b.HasIndex("ApplicationId", "DisplayOrder")
                        .HasDatabaseName("IX_Founders_ApplicationId_DisplayOrder");

                    b.ToTable("Founders");
                });

            modelBuilder.Entity("nsia.Models.Application", b =>
                {
                    b.OwnsOne("nsia.Models.SocialMedia", "SocialMedia", b1 =>
                        {
                            b1.Property<Guid>("ApplicationId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Facebook")
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("SocialMedia_Facebook");

                            b1.Property<string>("Instagram")
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("SocialMedia_Instagram");

                            b1.Property<string>("LinkedIn")
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("SocialMedia_LinkedIn");

                            b1.Property<string>("Twitter")
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("SocialMedia_Twitter");

                            b1.HasKey("ApplicationId");

                            b1.ToTable("Applications");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");
                        });

                    b.Navigation("SocialMedia")
                        .IsRequired();
                });

            modelBuilder.Entity("nsia.Models.ApplicationDocument", b =>
                {
                    b.HasOne("nsia.Models.Application", "Application")
                        .WithMany("Documents")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("nsia.Models.Founder", b =>
                {
                    b.HasOne("nsia.Models.Application", "Application")
                        .WithMany("Founders")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("nsia.Models.Application", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Founders");
                });
#pragma warning restore 612, 618
        }
    }
}
